SEXP savvy_init_runtime__ffi(DllInfo* c_arg___dll_info);

// methods and associated functions for DataFusionRDataFrame
SEXP savvy_DataFusionRDataFrame_print__ffi(SEXP self__);
SEXP savvy_DataFusionRDataFrame_logical_plan__ffi(SEXP self__);
SEXP savvy_DataFusionRDataFrame_collect__ffi(SEXP self__);
SEXP savvy_DataFusionRDataFrame_limit__ffi(SEXP self__, SEXP c_arg__n, SEXP c_arg__offset);
SEXP savvy_DataFusionRDataFrame_select_columns__ffi(SEXP self__, SEXP c_arg__columns);
SEXP savvy_DataFusionRDataFrame_select__ffi(SEXP self__, SEXP c_arg__exprs);
SEXP savvy_DataFusionRDataFrame_aggregate__ffi(SEXP self__, SEXP c_arg__group_expr, SEXP c_arg__aggr_expr);
SEXP savvy_DataFusionRDataFrame_dim__ffi(SEXP self__);
SEXP savvy_DataFusionRDataFrame_names__ffi(SEXP self__);

// methods and associated functions for DataFusionRExpr
SEXP savvy_DataFusionRExpr_ident__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExpr_lit__ffi(SEXP c_arg__x);
SEXP savvy_DataFusionRExpr_col__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExpr_wildcard__ffi(void);
SEXP savvy_DataFusionRExpr_print__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_and__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_bitwise_and__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_bitwise_or__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_bitwise_shift_left__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_bitwise_shift_right__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_or__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_placeholder__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExpr_add__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_sub__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_mul__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_div__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_reminder__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_lt__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_lt_eq__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_gt__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_gt_eq__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_eq__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_not_eq__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_bitand__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_bitor__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_bitxor__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_field__ffi(SEXP self__, SEXP c_arg__name);
SEXP savvy_DataFusionRExpr_index__ffi(SEXP self__, SEXP c_arg__key);
SEXP savvy_DataFusionRExpr_range__ffi(SEXP self__, SEXP c_arg__start, SEXP c_arg__stop);
SEXP savvy_DataFusionRExpr_like__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_not_like__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_ilike__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_not_ilike__ffi(SEXP self__, SEXP c_arg__rhs);
SEXP savvy_DataFusionRExpr_between__ffi(SEXP self__, SEXP c_arg__low, SEXP c_arg__high);
SEXP savvy_DataFusionRExpr_not_between__ffi(SEXP self__, SEXP c_arg__low, SEXP c_arg__high);
SEXP savvy_DataFusionRExpr_alias__ffi(SEXP self__, SEXP c_arg__name);
SEXP savvy_DataFusionRExpr_in_list__ffi(SEXP self__, SEXP c_arg__list, SEXP c_arg__negated);
SEXP savvy_DataFusionRExpr_neg__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_not__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_null__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_not_null__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_true__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_not_true__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_false__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_not_false__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_bitwise_xor__ffi(SEXP self__, SEXP c_arg__right);
SEXP savvy_DataFusionRExpr_is_unknown__ffi(SEXP self__);
SEXP savvy_DataFusionRExpr_is_not_unknown__ffi(SEXP self__);

// methods and associated functions for DataFusionRExprFunctions
SEXP savvy_DataFusionRExprFunctions_approx_distinct__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_approx_percentile_cont__ffi(SEXP c_arg__expr, SEXP c_arg__percentile);
SEXP savvy_DataFusionRExprFunctions_approx_percentile_cont_with_weight__ffi(SEXP c_arg__expr, SEXP c_arg__weight_expr, SEXP c_arg__percentile);
SEXP savvy_DataFusionRExprFunctions_array_agg__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_approx_median__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_avg__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_count__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_count_distinct__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_cube__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_max__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_median__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_min__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_rollup__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_stddev__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_sum__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_array_append__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_concat__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_array_dims__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_distinct__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_element__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_empty__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_except__ffi(SEXP c_arg__first_array, SEXP c_arg__second_array);
SEXP savvy_DataFusionRExprFunctions_array_has__ffi(SEXP c_arg__first_array, SEXP c_arg__second_array);
SEXP savvy_DataFusionRExprFunctions_array_has_all__ffi(SEXP c_arg__first_array, SEXP c_arg__second_array);
SEXP savvy_DataFusionRExprFunctions_array_has_any__ffi(SEXP c_arg__first_array, SEXP c_arg__second_array);
SEXP savvy_DataFusionRExprFunctions_array_intersect__ffi(SEXP c_arg__first_array, SEXP c_arg__second_array);
SEXP savvy_DataFusionRExprFunctions_array_ndims__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_pop_back__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_pop_front__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_position__ffi(SEXP c_arg__array, SEXP c_arg__element, SEXP c_arg__index);
SEXP savvy_DataFusionRExprFunctions_array_positions__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_prepend__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_remove__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_remove_all__ffi(SEXP c_arg__array, SEXP c_arg__element);
SEXP savvy_DataFusionRExprFunctions_array_remove_n__ffi(SEXP c_arg__array, SEXP c_arg__element, SEXP c_arg__max);
SEXP savvy_DataFusionRExprFunctions_array_repeat__ffi(SEXP c_arg__array, SEXP c_arg__count);
SEXP savvy_DataFusionRExprFunctions_array_replace__ffi(SEXP c_arg__array, SEXP c_arg__from, SEXP c_arg__to);
SEXP savvy_DataFusionRExprFunctions_array_replace_all__ffi(SEXP c_arg__array, SEXP c_arg__from, SEXP c_arg__to);
SEXP savvy_DataFusionRExprFunctions_array_replace_n__ffi(SEXP c_arg__array, SEXP c_arg__from, SEXP c_arg__to, SEXP c_arg__max);
SEXP savvy_DataFusionRExprFunctions_array_resize__ffi(SEXP c_arg__array, SEXP c_arg__size, SEXP c_arg__value);
SEXP savvy_DataFusionRExprFunctions_array_reverse__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_array_slice__ffi(SEXP c_arg__array, SEXP c_arg__begin, SEXP c_arg__end, SEXP c_arg__stride);
SEXP savvy_DataFusionRExprFunctions_array_sort__ffi(SEXP c_arg__array, SEXP c_arg__desc, SEXP c_arg__null_first);
SEXP savvy_DataFusionRExprFunctions_array_to_string__ffi(SEXP c_arg__array, SEXP c_arg__delimiter);
SEXP savvy_DataFusionRExprFunctions_array_union__ffi(SEXP c_arg__array1, SEXP c_arg__array2);
SEXP savvy_DataFusionRExprFunctions_cardinality__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_flatten__ffi(SEXP c_arg__array);
SEXP savvy_DataFusionRExprFunctions_gen_series__ffi(SEXP c_arg__start, SEXP c_arg__stop, SEXP c_arg__step);
SEXP savvy_DataFusionRExprFunctions_make_array__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_range__ffi(SEXP c_arg__start, SEXP c_arg__stop, SEXP c_arg__step);
SEXP savvy_DataFusionRExprFunctions_string_to_array__ffi(SEXP c_arg__array, SEXP c_arg__delimiter, SEXP c_arg__null_string);
SEXP savvy_DataFusionRExprFunctions_arrow_cast__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_arrow_typeof__ffi(SEXP c_arg__arg1);
SEXP savvy_DataFusionRExprFunctions_coalesce__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_get_field__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_named_struct__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_nullif__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_nvl__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_nvl2__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2, SEXP c_arg__arg3);
SEXP savvy_DataFusionRExprFunctions_digest__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_md5__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_sha224__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_sha256__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_sha384__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_sha512__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_current_date__ffi(void);
SEXP savvy_DataFusionRExprFunctions_current_time__ffi(void);
SEXP savvy_DataFusionRExprFunctions_date_bin__ffi(SEXP c_arg__stride, SEXP c_arg__source, SEXP c_arg__origin);
SEXP savvy_DataFusionRExprFunctions_date_part__ffi(SEXP c_arg__part, SEXP c_arg__date);
SEXP savvy_DataFusionRExprFunctions_date_trunc__ffi(SEXP c_arg__part, SEXP c_arg__date);
SEXP savvy_DataFusionRExprFunctions_from_unixtime__ffi(SEXP c_arg__unixtime);
SEXP savvy_DataFusionRExprFunctions_make_date__ffi(SEXP c_arg__year, SEXP c_arg__month, SEXP c_arg__day);
SEXP savvy_DataFusionRExprFunctions_now__ffi(void);
SEXP savvy_DataFusionRExprFunctions_to_char__ffi(SEXP c_arg__datetime, SEXP c_arg__format);
SEXP savvy_DataFusionRExprFunctions_to_date__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_timestamp__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_timestamp_micros__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_timestamp_millis__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_timestamp_nanos__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_timestamp_seconds__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_to_unixtime__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_decode__ffi(SEXP c_arg__input, SEXP c_arg__encoding);
SEXP savvy_DataFusionRExprFunctions_encode__ffi(SEXP c_arg__input, SEXP c_arg__encoding);
SEXP savvy_DataFusionRExprFunctions_abs__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_acos__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_acosh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_asin__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_asinh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_atan__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_atan2__ffi(SEXP c_arg__x, SEXP c_arg__y);
SEXP savvy_DataFusionRExprFunctions_atanh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_cbrt__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_ceil__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_cos__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_cosh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_cot__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_degrees__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_exp__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_factorial__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_floor__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_gcd__ffi(SEXP c_arg__x, SEXP c_arg__y);
SEXP savvy_DataFusionRExprFunctions_isnan__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_iszero__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_lcm__ffi(SEXP c_arg__x, SEXP c_arg__y);
SEXP savvy_DataFusionRExprFunctions_ln__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_log__ffi(SEXP c_arg__base, SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_log2__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_log10__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_nanvl__ffi(SEXP c_arg__x, SEXP c_arg__y);
SEXP savvy_DataFusionRExprFunctions_pi__ffi(void);
SEXP savvy_DataFusionRExprFunctions_power__ffi(SEXP c_arg__base, SEXP c_arg__exponent);
SEXP savvy_DataFusionRExprFunctions_radians__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_random__ffi(void);
SEXP savvy_DataFusionRExprFunctions_round__ffi(SEXP c_arg__num, SEXP c_arg__decimal_place);
SEXP savvy_DataFusionRExprFunctions_signum__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_sin__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_sinh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_sqrt__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_tan__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_tanh__ffi(SEXP c_arg__num);
SEXP savvy_DataFusionRExprFunctions_trunc__ffi(SEXP c_arg__num, SEXP c_arg__decimal_place);
SEXP savvy_DataFusionRExprFunctions_regexp_like__ffi(SEXP c_arg__string, SEXP c_arg__pattern);
SEXP savvy_DataFusionRExprFunctions_regexp_match__ffi(SEXP c_arg__string, SEXP c_arg__pattern);
SEXP savvy_DataFusionRExprFunctions_regexp_replace__ffi(SEXP c_arg__string, SEXP c_arg__pattern, SEXP c_arg__replacement, SEXP c_arg__flags);
SEXP savvy_DataFusionRExprFunctions_ascii__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_bit_length__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_btrim__ffi(SEXP c_arg__string, SEXP c_arg__trim_str);
SEXP savvy_DataFusionRExprFunctions_chr__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_concat__ffi(SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_concat_ws__ffi(SEXP c_arg__delimiter, SEXP c_arg__args);
SEXP savvy_DataFusionRExprFunctions_ends_with__ffi(SEXP c_arg__string, SEXP c_arg__suffix);
SEXP savvy_DataFusionRExprFunctions_initcap__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_levenshtein__ffi(SEXP c_arg__arg1, SEXP c_arg__arg2);
SEXP savvy_DataFusionRExprFunctions_lower__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_ltrim__ffi(SEXP c_arg__string, SEXP c_arg__trim_str);
SEXP savvy_DataFusionRExprFunctions_octet_length__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_overlay__ffi(SEXP c_arg__string, SEXP c_arg__replacement, SEXP c_arg__pos, SEXP c_arg__count);
SEXP savvy_DataFusionRExprFunctions_repeat__ffi(SEXP c_arg__string, SEXP c_arg__n);
SEXP savvy_DataFusionRExprFunctions_replace__ffi(SEXP c_arg__string, SEXP c_arg__from, SEXP c_arg__to);
SEXP savvy_DataFusionRExprFunctions_rtrim__ffi(SEXP c_arg__string, SEXP c_arg__trim_str);
SEXP savvy_DataFusionRExprFunctions_split_part__ffi(SEXP c_arg__string, SEXP c_arg__delimiter, SEXP c_arg__index);
SEXP savvy_DataFusionRExprFunctions_starts_with__ffi(SEXP c_arg__string, SEXP c_arg__prefix);
SEXP savvy_DataFusionRExprFunctions_to_hex__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_trim__ffi(SEXP c_arg__string, SEXP c_arg__trim_str);
SEXP savvy_DataFusionRExprFunctions_upper__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_uuid__ffi(void);
SEXP savvy_DataFusionRExprFunctions_char_length__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_character_length__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_find_in_set__ffi(SEXP c_arg__string, SEXP c_arg__strlist);
SEXP savvy_DataFusionRExprFunctions_instr__ffi(SEXP c_arg__string, SEXP c_arg__substring);
SEXP savvy_DataFusionRExprFunctions_left__ffi(SEXP c_arg__string, SEXP c_arg__n);
SEXP savvy_DataFusionRExprFunctions_length__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_lpad__ffi(SEXP c_arg__string, SEXP c_arg__padding_str);
SEXP savvy_DataFusionRExprFunctions_position__ffi(SEXP c_arg__string, SEXP c_arg__substring);
SEXP savvy_DataFusionRExprFunctions_reverse__ffi(SEXP c_arg__arg);
SEXP savvy_DataFusionRExprFunctions_right__ffi(SEXP c_arg__string, SEXP c_arg__n);
SEXP savvy_DataFusionRExprFunctions_rpad__ffi(SEXP c_arg__string, SEXP c_arg__padding_str);
SEXP savvy_DataFusionRExprFunctions_strpos__ffi(SEXP c_arg__string, SEXP c_arg__substring);
SEXP savvy_DataFusionRExprFunctions_substr__ffi(SEXP c_arg__string, SEXP c_arg__position);
SEXP savvy_DataFusionRExprFunctions_substr_index__ffi(SEXP c_arg__string, SEXP c_arg__delimiter, SEXP c_arg__count);
SEXP savvy_DataFusionRExprFunctions_substring__ffi(SEXP c_arg__string, SEXP c_arg__position, SEXP c_arg__length);
SEXP savvy_DataFusionRExprFunctions_translate__ffi(SEXP c_arg__string, SEXP c_arg__from, SEXP c_arg__to);

// methods and associated functions for DataFusionRExprs
SEXP savvy_DataFusionRExprs_new__ffi(SEXP c_arg__capacity);
SEXP savvy_DataFusionRExprs_add_expr__ffi(SEXP self__, SEXP c_arg__expr);
SEXP savvy_DataFusionRExprs_print__ffi(SEXP self__);

// methods and associated functions for DataFusionRSessionContext
SEXP savvy_DataFusionRSessionContext_new__ffi(void);
SEXP savvy_DataFusionRSessionContext_create_data_frame__ffi(SEXP self__, SEXP c_arg__raw_stream, SEXP c_arg__table_name);
SEXP savvy_DataFusionRSessionContext_sql__ffi(SEXP self__, SEXP c_arg__sql);
SEXP savvy_DataFusionRSessionContext_register_parquet__ffi(SEXP self__, SEXP c_arg__name, SEXP c_arg__path, SEXP c_arg__file_extension, SEXP c_arg__parquet_pruning, SEXP c_arg__skip_metadata);
SEXP savvy_DataFusionRSessionContext_register_csv__ffi(SEXP self__, SEXP c_arg__name, SEXP c_arg__path, SEXP c_arg__has_header, SEXP c_arg__delimiter, SEXP c_arg__quote, SEXP c_arg__escape, SEXP c_arg__schema_infer_max_records, SEXP c_arg__file_extension);

// methods and associated functions for RawArrayStream
SEXP savvy_RawArrayStream_new_without_init__ffi(void);