test_that("expressions", {
  e <- function(...) {
    capture.output(print(datafusion_exprs(...)))
  }

  expect_equal(e(col("foo")), "foo")
  expect_equal(e(col("foo")$alias("bar")), "foo AS bar")

  expect_equal(e(lit(1)), "Float64(1)")
  expect_equal(e(lit(1L)), "Int32(1)")
  expect_equal(e(lit(TRUE)), "Boolean(true)")
  expect_equal(e(lit("a")), 'Utf8("a")')

  # unary
  expect_equal(e(+col("foo")), "foo")
  expect_equal(e(-col("foo")), "(- foo)")
  expect_equal(e(!col("foo")), "NOT foo")
  expect_equal(e(col("foo")$is_null()), "foo IS NULL")
  expect_equal(e(col("foo")$is_not_null()), "foo IS NOT NULL")
  expect_equal(e(col("foo")$is_true()), "foo IS TRUE")
  expect_equal(e(col("foo")$is_false()), "foo IS FALSE")

  # binary
  expect_equal(e(col("foo") +  col("bar")), "foo + bar" )
  expect_equal(e(col("foo") -  col("bar")), "foo - bar" )
  expect_equal(e(col("foo") *  col("bar")), "foo * bar" )
  expect_equal(e(col("foo") /  col("bar")), "foo / bar" )
  expect_equal(e(col("foo") %% col("bar")), "foo % bar" )
  expect_equal(e(col("foo") == col("bar")), "foo = bar" )
  expect_equal(e(col("foo") != col("bar")), "foo != bar")
  expect_equal(e(col("foo") <  col("bar")), "foo < bar" )
  expect_equal(e(col("foo") <= col("bar")), "foo <= bar")
  expect_equal(e(col("foo") >  col("bar")), "foo > bar" )
  expect_equal(e(col("foo") >= col("bar")), "foo >= bar")
  expect_equal(e(col("foo") &  col("bar")), "foo & bar" )
  expect_equal(e(col("foo") |  col("bar")), "foo | bar" )
  expect_equal(e(col("foo") ^  col("bar")), "foo BIT_XOR bar")
  expect_equal(e(col("foo") && col("bar")), "foo AND bar")
  expect_equal(e(col("foo") || col("bar")), "foo OR bar")

  expect_equal(e(col("foo")[["a"]]), '(foo)[a]')            # field
  expect_equal(e(col("foo")[lit("a")]), '(foo)[Utf8("a")]') # index
  expect_equal(e(col("foo")[1:3]), '(foo)[Int32(1):Int32(3):Int64(1)]') # range

  # % needs to be escaped
  expect_equal(e(col("foo")$like(lit("prefix_%"))),      'foo LIKE Utf8("prefix_%")')
  expect_equal(e(col("foo")$not_like(lit("prefix_%"))),  'foo NOT LIKE Utf8("prefix_%")')
  expect_equal(e(col("foo")$ilike(lit("prefix_%"))),     'foo ILIKE Utf8("prefix_%")')
  expect_equal(e(col("foo")$not_ilike(lit("prefix_%"))), 'foo NOT ILIKE Utf8("prefix_%")')

  expect_equal(e(col("foo")$between(lit(0), lit(100))),     'foo BETWEEN Float64(0) AND Float64(100)')
  expect_equal(e(col("foo")$not_between(lit(0), lit(100))), 'foo NOT BETWEEN Float64(0) AND Float64(100)')

  expect_equal(e(col("foo") %in% c(lit("a"), lit("b"), lit("c"))), 'foo IN ([Utf8("a"), Utf8("b"), Utf8("c")])')
})

test_that("function expressions", {
  e <- function(...) {
    capture.output(print(datafusion_exprs(...)))
  }

  # core
  expect_equal(e(arrow_cast(col("foo"), lit("Utf8"))),                  'arrow_cast(foo, Utf8("Utf8"))')
  expect_equal(e(arrow_typeof(col("foo"))),                             "arrow_typeof(foo)")
  expect_equal(e(coalesce(col("foo"), col("bar"), lit("default"))),     'coalesce(foo, bar, Utf8("default"))')
  expect_equal(e(get_field(col("foo"), col("bar"))),                    "get_field(foo, bar)")
  expect_equal(e(named_struct(lit("A"), col("a"), lit("B"), col("b"))), 'named_struct(Utf8("A"), a, Utf8("B"), b)')
  expect_equal(e(nullif(col("foo"), lit("NULL"))),                      'nullif(foo, Utf8("NULL"))')
  expect_equal(e(nvl(col("foo"), lit("default"))),                      'nvl(foo, Utf8("default"))')
  expect_equal(e(nvl2(col("foo"), col("bar"), lit("default"))),         'nvl2(foo, bar, Utf8("default"))')

  # crypto
  expect_equal(e(digest(col("foo"), lit("bar"))),    'digest(foo, Utf8("bar"))')
  expect_equal(e(md5(col("foo"))),                   "md5(foo)")
  expect_equal(e(sha224(col("foo"))),                "sha224(foo)")
  expect_equal(e(sha256(col("foo"))),                "sha256(foo)")
  expect_equal(e(sha384(col("foo"))),                "sha384(foo)")
  expect_equal(e(sha512(col("foo"))),                "sha512(foo)")

  #datetime
  expect_equal(e(current_date()),                                 "current_date()")
  expect_equal(e(current_time()),                                 "current_time()")
  expect_equal(e(date_bin(col("foo"), col("bar"), col("baz"))),   "date_bin(foo, bar, baz)")
  expect_equal(e(date_part(col("foo"), col("bar"))),              "date_part(foo, bar)")
  expect_equal(e(date_trunc(lit("week"), col("bar"))),            'date_trunc(Utf8("week"), bar)')
  expect_equal(e(from_unixtime(col("foo"))),                      "from_unixtime(foo)")
  expect_equal(e(make_date(col("foo"), col("bar"), col("baz"))),  "make_date(foo, bar, baz)")
  expect_equal(e(now()),                                          "now()")
  expect_equal(e(to_char(col("bar"), lit("%Y%m"))),               'to_char(bar, Utf8("%Y%m"))')

  expect_equal(e(to_date(col("bar"))),                                        'to_date(bar)')
  expect_equal(e(to_date(col("bar"), lit("%Y%m"))),                           'to_date(bar, Utf8("%Y%m"))')
  expect_equal(e(to_date(col("bar"), lit("%Y%m"),lit("%Y-%m"))),              'to_date(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_timestamp(col("bar"), lit("%Y%m"),lit("%Y-%m"))),         'to_timestamp(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_timestamp_micros(col("bar"), lit("%Y%m"),lit("%Y-%m"))),  'to_timestamp_micros(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_timestamp_millis(col("bar"), lit("%Y%m"),lit("%Y-%m"))),  'to_timestamp_millis(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_timestamp_nanos(col("bar"), lit("%Y%m"),lit("%Y-%m"))),   'to_timestamp_nanos(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_timestamp_seconds(col("bar"), lit("%Y%m"),lit("%Y-%m"))), 'to_timestamp_seconds(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')
  expect_equal(e(to_unixtime(col("bar"), lit("%Y%m"),lit("%Y-%m"))),          'to_unixtime(bar, Utf8("%Y%m"), Utf8("%Y-%m"))')

  # math
  expect_equal(e(abs(col("foo"))),                   "abs(foo)")
  expect_equal(e(acos(col("foo"))),                  "acos(foo)")
  expect_equal(e(acosh(col("foo"))),                 "acosh(foo)")
  expect_equal(e(asin(col("foo"))),                  "asin(foo)")
  expect_equal(e(asinh(col("foo"))),                 "asinh(foo)")
  expect_equal(e(atan(col("foo"))),                  "atan(foo)")
  expect_equal(e(atan2(col("foo"), col("bar"))),     "atan2(foo, bar)")
  expect_equal(e(atanh(col("foo"))),                 "atanh(foo)")
  expect_equal(e(cbrt(col("foo"))),                  "cbrt(foo)")
  expect_equal(e(ceil(col("foo"))),                  "ceil(foo)")
  expect_equal(e(cos(col("foo"))),                   "cos(foo)")
  expect_equal(e(cosh(col("foo"))),                  "cosh(foo)")
  expect_equal(e(cot(col("foo"))),                   "cot(foo)")
  expect_equal(e(degrees(col("foo"))),               "degrees(foo)")
  expect_equal(e(exp(col("foo"))),                   "exp(foo)")
  expect_equal(e(factorial(col("foo"))),             "factorial(foo)")
  expect_equal(e(floor(col("foo"))),                 "floor(foo)")
  expect_equal(e(gcd(col("foo"), col("bar"))),       "gcd(foo, bar)")
  expect_equal(e(isnan(col("foo"))),                 "isnan(foo)")
  expect_equal(e(iszero(col("foo"))),                "iszero(foo)")
  expect_equal(e(lcm(col("foo"), col("bar"))),       "lcm(foo, bar)")
  expect_equal(e(ln(col("foo"))),                    "ln(foo)")
  expect_equal(e(log(lit(16L), col("foo"))),         "log(Int32(16), foo)")
  expect_equal(e(log2(col("foo"))),                  "log2(foo)")
  expect_equal(e(log10(col("foo"))),                 "log10(foo)")
  expect_equal(e(nanvl(col("foo"), col("bar"))),     "nanvl(foo, bar)")
  expect_equal(e(pi()),                              "pi()")
  expect_equal(e(power(col("foo"), lit(2.5))),       "power(foo, Float64(2.5))")
  expect_equal(e(radians(col("foo"))),               "radians(foo)")
  expect_equal(e(random()),                          "random()")
  expect_equal(e(round(col("foo"))),                 "round(foo)")
  expect_equal(e(round(col("foo"), lit(2L))),        "round(foo, Int32(2))")
  expect_equal(e(signum(col("foo"))),                "signum(foo)")
  expect_equal(e(sin(col("foo"))),                   "sin(foo)")
  expect_equal(e(sinh(col("foo"))),                  "sinh(foo)")
  expect_equal(e(sqrt(col("foo"))),                  "sqrt(foo)")
  expect_equal(e(tan(col("foo"))),                   "tan(foo)")
  expect_equal(e(tanh(col("foo"))),                  "tanh(foo)")
  expect_equal(e(trunc(col("foo"))),                 "trunc(foo)")
  expect_equal(e(trunc(col("foo"), lit(2L))),        "trunc(foo, Int32(2))")

  # regex
  expect_equal(e(regexp_like(col("foo"), lit("prefix_%"))),      'regexp_like(foo, Utf8("prefix_%"))')
  expect_equal(e(regexp_match(col("foo"), lit("prefix_.*"))),    'regexp_match(foo, Utf8("prefix_.*"))')
  expect_equal(e(regexp_replace(col("foo"), lit("prefix_(.*)"), lit("\\1"))),
               'regexp_replace(foo, Utf8("prefix_(.*)"), Utf8("\\1"), Utf8("g"))')
  expect_equal(e(regexp_replace(col("foo"), lit("prefix_(.*)"), lit("\\1"), lit("gi"))),
               'regexp_replace(foo, Utf8("prefix_(.*)"), Utf8("\\1"), Utf8("gi"))')
  # string
  expect_equal(e(ascii(col("foo"))),                               "ascii(foo)")
  expect_equal(e(bit_length(col("foo"))),                          "bit_length(foo)")
  expect_equal(e(btrim(col("foo"))),                               "btrim(foo)")
  expect_equal(e(btrim(col("foo"), lit("f"))),                     'btrim(foo, Utf8("f"))')
  expect_equal(e(chr(col("foo"))),                                 "chr(foo)")
  expect_equal(e(concat(col("foo"), col("bar"))),                  "concat(foo, bar)")
  expect_equal(e(concat(col("foo"), lit("-"), col("bar"))),        'concat(foo, Utf8("-"), bar)')
  expect_equal(e(concat_ws(lit("-"), col("foo"), col("bar"))),     'concat_ws(Utf8("-"), foo, bar)')
  expect_equal(e(ends_with(col("foo"), lit(".txt"))),              'ends_with(foo, Utf8(".txt"))')
  expect_equal(e(initcap(col("foo"))),                             "initcap(foo)")
  expect_equal(e(levenshtein(col("foo"), col("bar"))),             "levenshtein(foo, bar)")
  expect_equal(e(lower(col("foo"))),                               "lower(foo)")
  expect_equal(e(ltrim(col("foo"))),                               "ltrim(foo)")
  expect_equal(e(ltrim(col("foo"), lit("f"))),                     'ltrim(foo, Utf8("f"))')
  expect_equal(e(octet_length(col("foo"))),                        "octet_length(foo)")
  expect_equal(e(overlay(col("foo"), lit("x"), lit(2L))),          'overlay(foo, Utf8("x"), Int32(2))')
  expect_equal(e(overlay(col("foo"), lit("x"), lit(2L), lit(3L))), 'overlay(foo, Utf8("x"), Int32(2), Int32(3))')
  expect_equal(e(str_repeat(col("foo"), lit(3L))),                 'repeat(foo, Int32(3))')
  expect_equal(e(replace(col("foo"),  lit("x"),  lit("y"))),       'replace(foo, Utf8("x"), Utf8("y"))')
  expect_equal(e(rtrim(col("foo"))),                               "rtrim(foo)")
  expect_equal(e(rtrim(col("foo"), lit("f"))),                     'rtrim(foo, Utf8("f"))')
  expect_equal(e(split_part(col("foo"), lit(","), lit(2L))),       'split_part(foo, Utf8(","), Int32(2))')
  expect_equal(e(starts_with(col("foo"), lit("pre_"))),            'starts_with(foo, Utf8("pre_"))')
  expect_equal(e(to_hex(col("foo"))),                              "to_hex(foo)")
  expect_equal(e(trim(col("foo"))),                                "btrim(foo)")
  expect_equal(e(trim(col("foo"), lit("f"))),                      'btrim(foo, Utf8("f"))')
  expect_equal(e(upper(col("foo"))),                               "upper(foo)")
  expect_equal(e(uuid()),                                          "uuid()")

  # unicode
  expect_equal(e(char_length(col("foo"))),                      "character_length(foo)")
  expect_equal(e(character_length(col("foo"))),                 "character_length(foo)")
  expect_equal(e(find_in_set(col("foo"), lit("x,y,z"))),        'find_in_set(foo, Utf8("x,y,z"))')
  expect_equal(e(instr(col("foo"), lit("the"))),                'strpos(foo, Utf8("the"))')
  expect_equal(e(left(col("foo"), lit(10L))),                   'left(foo, Int32(10))')
  expect_equal(e(length(col("foo"))),                           "character_length(foo)")
  expect_equal(e(lpad(col("foo"), lit("*"))),                   'lpad(foo, Utf8("*"))')
  expect_equal(e(position(col("foo"), lit("the"))),             'strpos(foo, Utf8("the"))')
  expect_equal(e(reverse(col("foo"))),                          "reverse(foo)")
  expect_equal(e(right(col("foo"), lit(10L))),                  'right(foo, Int32(10))')
  expect_equal(e(rpad(col("foo"), lit("*"))),                   'rpad(foo, Utf8("*"))')
  expect_equal(e(strpos(col("foo"), lit("the"))),               'strpos(foo, Utf8("the"))')
  expect_equal(e(substr(col("foo"), lit(10L))),                 'substr(foo, Int32(10))')
  expect_equal(e(substr_index(col("foo"), lit(","), lit(10L))), 'substr_index(foo, Utf8(","), Int32(10))')
  expect_equal(e(substring(col("foo"), lit(3L), lit(10L))),     'substr(foo, Int32(3), Int32(10))')
  expect_equal(e(translate(col("a"), lit("bc"), lit("xx"))),    'translate(a, Utf8("bc"), Utf8("xx"))')

})
